# ==========================================
# Collide User Service Docker Compose 配置示例
# 用于本地开发和测试环境部署
# ==========================================

version: '3.8'

services:

  # 用户微服务
  collide-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collide-api-service
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      # 覆盖某些Docker特定的配置
      HOST: "0.0.0.0"
      # 如果使用Docker内部网络，需要调整数据库和Nacos地址
      DATABASE_URL: "${DATABASE_URL}"
      NACOS_SERVER: "${NACOS_SERVER}"
    
    depends_on:
      - mysql
      - redis
    
    networks:
      collide-network:
        ipv4_address: 172.20.3.15
      
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  collide-network:
    external: true
    name: collide-network